#!/usr/bin/env node

// Generates extension/sites/github.css from GitHub's Primer dark theme.
// GitHub styles everything through Primer tokens, so remapping the tokens
// recolors the whole site. Re-run when GitHub ships new tokens:
//
//   tools/gen-github.js            # fetches the current dark theme sheet
//   tools/gen-github.js dark.css   # or uses a saved copy

const fs = require("fs");
const path = require("path");
const P = require("../extension/palette.js");

const OUT = path.join(__dirname, "../extension/sites/github.css");

// Semantic token families -> palette hue
const HUE_HINTS = [
  [/accent|link|focus|selected|primary|checked/i, "accent"],
  [/success|open/i, "green"],
  [/danger|closed|deletion|deleted|invalid|carriage/i, "red"],
  [/attention|warning/i, "yellow"],
  [/severe|changed/i, "orange"],
  [/done|sponsors|upsell/i, "magenta"],
  [/addition|inserted/i, "green"],
];

const SYNTAX = {
  comment: "var(--om-fg-faint)", constant: "var(--om-blue)", entity: "var(--om-magenta)",
  "entity-tag": "var(--om-green)", entityTag: "var(--om-green)", keyword: "var(--om-red)",
  "storage-modifier-import": "var(--om-fg)", storageModifierImport: "var(--om-fg)",
  string: "var(--om-cyan)", "string-regexp": "var(--om-cyan)", stringRegexp: "var(--om-cyan)",
  variable: "var(--om-orange)", "markup-heading": "var(--om-blue)", "markup-list": "var(--om-yellow)",
  "markup-bold": "var(--om-fg)", "markup-italic": "var(--om-fg)",
  "meta-diff-range": "var(--om-magenta)", metaDiffRange: "var(--om-magenta)",
};

const ANSI = { black: "var(--om-surface-3)", white: "var(--om-fg)", gray: "var(--om-fg-faint)" };

function role(name) {
  if (/fgColor|iconColor|-text$|Color-logo|^--color-ansi|^--ansi|prettylights/i.test(name)) return "fg";
  if (/border|outline/i.test(name)) return "border";
  return "bg";
}

function hint(name) {
  if (/onEmphasis|onInverse|primary-(fg|icon)Color|checked-fgColor/i.test(name)) return { expr: "var(--om-fg-strong)" };
  const syntax = name.match(/prettylights-syntax-(.+)$/);
  if (syntax && SYNTAX[syntax[1]]) return { expr: SYNTAX[syntax[1]] };
  const ansi = name.match(/ansi-(black|white|gray|red|green|yellow|blue|magenta|cyan)/i);
  if (ansi) return ANSI[ansi[1]] ? { expr: ANSI[ansi[1]] } : { hue: ansi[1] };
  for (const [re, hue] of HUE_HINTS) if (re.test(name)) return { hue };
  return {};
}

async function main() {
  const src = process.argv[2];
  let css;
  if (src) {
    css = fs.readFileSync(src, "utf8");
  } else {
    const html = await (await fetch("https://github.com/")).text();
    const href = html.match(/https:\/\/github\.githubassets\.com\/assets\/dark-[0-9a-f]+\.css/)[0];
    css = await (await fetch(href)).text();
  }

  const block = css.match(/\[data-color-mode=dark\]\[data-dark-theme=dark\][^{]*\{([^}]*)\}/)[1];
  const tokens = [...block.matchAll(/(--[\w-]+):([^;]+)/g)].map((m) => [m[1], m[2].trim()]);
  const get = (n) => P.colorsIn(tokens.find(([k]) => k === n)[1])[0];
  const ctx = { bgL: P.lightness(get("--bgColor-default")), fgL: P.lightness(get("--fgColor-default")) };

  const lines = [];
  for (const [name, value] of tokens) {
    if (/shadow|-white$|-black$/i.test(name)) continue;
    const mapped = P.remapValue(value, role(name), ctx, hint(name));
    if (mapped) lines.push(`  ${name}: ${mapped} !important;`);
  }

  fs.writeFileSync(OUT, `/* GitHub: generated by tools/gen-github.js from Primer's dark theme tokens.
   Do not edit by hand. */

html[data-omarchy-themed],
html[data-omarchy-themed] [data-color-mode] {
${lines.join("\n")}
}
`);
  console.log(`${lines.length} tokens -> ${path.relative(process.cwd(), OUT)}`);
}

main();
